### ISSUE TITLE
hedera_getNodeAddresses

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#16]
**Describe the spec as defined in HIP-820**
While constructing a transaction for transmission to a controller, a dApp needs to choose which Hedera Network node shall receive the transaction prior to signing (this is a requirement of the Hedera API Protocol). While a dApp can easily obtain a list of potential Hedera Nodes, a controller may not have an all-inclusive list nor a path to the node’s gRPC endpoint. The hedera_getNodeAddresses method allows a dApp to request a list of node wallet addresses known to the controller. The controller should only include nodes in this list that it is willing and able to submit transactions to at the time of the request.

Parameters
This method requires no input parameters. The [CAIP-217](https://chainagnostic.org/CAIPs/caip-217) Scope property of the RPC call shall be used to identify which network shall be assumed when obtaining the list of known network nodes.

Returns
nodes – an array of strings formatted in the <shard>.<realm>.<num> format identifying an Hedera Address. The controller should only return known nodes that it can communicate with to submit transactions.

**Does this issue add new functionality to this repository or change functionality (such as a change in function signature)**
This is new functionality

**Comment by itsbrandondev** [comment]
hey @BeeJeeNinja any update on this issue?
