### ISSUE TITLE
EIP:155 Example

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#20]
**Is your feature request related to a problem? Please describe.**
The core of this library is focussed on implementing HIP-820 in addition to providing helper utilities for WalletConnect features. This issue is to implement WalletConnect using the EIP:155 (ethereum) namespace as an alternative to the Hedera <> WC JSON-RPC spec as defined in HIP-820.

**Describe the solution you'd like**
Add to the demo application functionality supported by the Hedera Eth compatible JSON-RPC relay.

**Describe alternatives you've considered**
We've considered not including this.

**Additional context**
For greatest interoperability, dApps / wallets could support both the Hedera namespace in addition to the ethereum namespace.

https://github.com/hashgraph/hedera-json-rpc-relay

https://swirldslabs.com/hashio/

**Comment by BeeJeeNinja** [comment]
https://swirldslabs.com/hashio/

**Comment by hgraphql** [comment]
closing this issue as not required for completion of the Hedera JSON-RPC, we'll priortize the Hedera JSON-RPC until that is complete
