### ISSUE TITLE
WalletConnect Session Management helpers for dApps

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#21]
**Is your feature request related to a problem? Please describe.**
A session management helper has been added to https://github.com/hgraph-io/hedera-walletconnect-utils/blob/main/src/DAppConnector.ts

We'd like to test, utilize, and extend this helper in the demo apps

**Describe the solution you'd like**
Provide an example using the DAppConnector

**Describe alternatives you've considered**

**Additional context**
Session management can be achieved directly with WC through event handling, though there are myriad possibilities. This connection helper intends to streamline the connection and session management process.

**Comment by itsbrandondev** [comment]
hey @hgraphql is there an update on this? i can close or extend deadline : )

**Comment by hgraphql** [comment]
closing as completed
