### ISSUE TITLE
release readiness

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#24]
adapt to the @hashgraph org standard procedures (including legal considerations) for publishing under @hashgraph org and to npm + other language package repositories

**Comment by itsbrandondev** [comment]
hey @hgraphql possible description for this:

_Adaptation of @hashgraph Organization's Standard Publishing Procedures: This issue focuses on modifying the existing standard procedures, including legal aspects, of the @hashgraph organization to facilitate the publication of projects under the @hashgraph namespace on npm and other language-specific package repositories. The goal is to ensure that the publishing process aligns with the organization's standards while considering the unique requirements of different package management systems._

**Comment by hgraphql** [comment]
@itsbrandondev Let's connect with Greg/ Ashe to get the full scope of what this repo needs to have in it / look like for it to pass the checks when moving to the @hashgraph organization

some of the config changes will come directly in the new repo location, though I think we can prepare here

**Comment by itsbrandondev** [comment]
ok sounds good @hgraphql ping me here when you wish to take action in that regard
