### ISSUE TITLE
Update WalletConnect repos

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#27]
there are 2 repos within the @walletconnect organization that need updating based on changes to our spec & implementation

 - https://github.com/WalletConnect/walletconnect-specs/pull/117

 - https://github.com/WalletConnect/web-examples/pull/269

**Comment by BeeJeeNinja** [comment]
I don't understand what needs to be done here. Please elaborate (we can discuss on a call)

**Comment by hgraphql** [comment]
> I don't understand what needs to be done here. Please elaborate (we can discuss on a call)

@BeeJeeNinja we created PRs that are now out of date, we'll eventually need to update these PRs

**Comment by hgraphql** [comment]
@BeeJeeNinja we can walk through on a call tomorrow if it's still unclear. though it'd be good to check out the PRs listed in the description above.

basically, we've followed the instructions for onboarding a new chain into WalletConnect. As we've changed our JSON-RPC spec, those PR's are now outdated. This ticket is to beginning updating those PR's

Please feel free to dive into this and break up into smaller issues

**Comment by hgraphql** [comment]
This is currently blocked

**Comment by hgraphql** [comment]
we are live with https://specs.walletconnect.com/2.0/blockchain-rpc/hedera-rpc

though still need to update https://github.com/WalletConnect/walletconnect-monorepo/pull/3415 and https://github.com/WalletConnect/web-examples/pull/269

**Comment by hgraphql** [comment]
closing these as merged. though a demo app in the wallet connect repository would still be useful as the original demo was outdated and therefore removed (a merge with 0 commits)

the specs are live!
