### ISSUE TITLE
Using esbuild in demo app imports @hashgraph/sdk node version

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#30]
**Describe the bug**
Using esbuild to build the demo app, there is a build error that expects node variables in a browser setting.

**To Reproduce**
1. in file `demo/src/wallet/main.ts`: `import { PrivateKey, AccountId } from '@hashgraph/sdk'`
2. Notice node errors:
3. `import { PrivateKey, AccountId } from '../../../node_modules/@hashgraph/sdk/src/browser.js'` does not throw these errors

**Expected behavior**
We expect this to work in the browser without issue

**Screenshots**
<img width="976" alt="Screenshot 2023-11-07 at 8 10 28 AM" src="https://github.com/hgraph-io/hedera-walletconnect-utils/assets/105378986/58a8f340-2ad1-46a4-beb9-762f321db160">

**Desktop (please complete the following information):**
 - node 18
 - any browser

**Additional context**
Esbuild has some configuration options that may fix this. Or potentially there is a config in the sdk that will help this.

**Comment by itsbrandondev** [comment]
hey @hgraphql should i get this added to the project and milestones?

**Comment by hgraphql** [comment]
> hey @hgraphql should i get this added to the project and milestones?

good callout just added the project and milestone. 

assigned @BeeJeeNinja

 - this is related to the other comment you've sent me in a DM
 
 the end import should be `import ... from '@hashgraph/sdk` at least in the library. (vs.  `import ... from '@hashgraph/sdk/src/browser.js`
  
 we may have to build for different contexts - here's an example: https://github.com/hgraph-io/sdk/blob/main/build.mjs
 
 I'm going to mark this as low priority for now
