### ISSUE TITLE
draft agenda

### ISSUE THREAD

**Issue by itsbrandondev** [hgraph-io/hedera-walletconnect-utils#31]
working on the [draft agenda](https://github.com/hgraph-io/hedera-walletconnect-utils/wiki/Work-Group-Meeting-%E2%80%90-Nov-10th-2023) for november's working group call @hgraphql

**Comment by itsbrandondev** [comment]
added more attendees

**Comment by itsbrandondev** [comment]
hey @hgraphql what do you think of this for votes?
* Make call recording & notes public (simple majority via Google Meet Poll)
* Approve milestones (simple majority via Google Meet Poll)
* 3 wallets integrated by dec 1st (verbal confirmation by wallets)

**Comment by hgraphql** [comment]
> hey @hgraphql what do you think of this for votes?
> 
> * Make call recording & notes public (simple majority via Google Meet Poll)
> * Approve milestones (simple majority via Google Meet Poll)
> * 3 wallets integrated by dec 1st (verbal confirmation by wallets)

@itsbrandondev what if we lean right into gh with https://github.com/hgraph-io/hedera-walletconnect-utils/discussions/categories/polls

**Comment by itsbrandondev** [comment]
i like the idea of that @hgraphql but i think for the purposes of getting things up to speed, it might be good for this call to capture agreement/consent while we have everyone present and then going forward, utilize this for async consensus. make sense?

**Comment by itsbrandondev** [comment]
ok @hgraphql i have added the votes to the agenda so we should be all good to go! let me know if we're good to close this issue and send the agenda to the group : )

**Comment by hgraphql** [comment]
> ok @hgraphql i have added the votes to the agenda so we should be all good to go! let me know if we're good to close this issue and send the agenda to the group : )

@itsbrandondev great, sounds good!
