### ISSUE TITLE
clean up issues (labels & templates)

### ISSUE THREAD

**Issue by itsbrandondev** [hgraph-io/hedera-walletconnect-utils#35]
hey @hgraphql im going to review issue templates and make modifications. going to also review all open issues and ensure proper labels and other metadata are assigned. i wont assign timetables. i wont assign milestones unless it is clear which milestone they belong to. will ping folks on any issues that need a bump.

**Comment by itsbrandondev** [comment]
hey @hgraphql i've done the following on this issue:

- reviewed all open issues and reviewed metadata for each, adding missing info (mostly labels)
- observed that things seem in fairly good order (moved back 2 weekly goals that were past due)
- most other metadata for issues is well attributed currently

i also recommend we remove the "wontfix" and "invalid" label as these might appear dismissive or discouraging from a community engagement perspective. a more constructive approach might be to explain why something is invalid or wont be fixed in the comments. but maybe there is another factor to justify these labels?

**Comment by hgraphql** [comment]
> hey @hgraphql i've done the following on this issue:
> 
> * reviewed all open issues and reviewed metadata for each, adding missing info (mostly labels)
> * observed that things seem in fairly good order (moved back 2 weekly goals that were past due)
> * most other metadata for issues is well attributed currently
> 
> i also recommend we remove the "wontfix" and "invalid" label as these might appear dismissive or discouraging from a community engagement perspective. a more constructive approach might be to explain why something is invalid or wont be fixed in the comments. but maybe there is another factor to justify these labels?

@itsbrandondev sounds good on the recommendations, these were github default labels

**Comment by itsbrandondev** [comment]
ok great @hgraphql i'll factor this in when making tweaks

**Comment by hgraphql** [comment]
@itsbrandondev closing this issue as it seems complete / stale

**Comment by itsbrandondev** [comment]
yes @hgraphql one thing i have left to do is to revise issue templates but that isn't a huge priority so its fine to close this 👍
