### ISSUE TITLE
Make demo:dev npm script

### ISSUE THREAD

**Issue by BeeJeeNinja** [hgraph-io/hedera-walletconnect-utils#38]
Right now in order to run the app, you need to do 2 things:
npm run build
npm run demo

Build is not watching changes. Each time you change something, you need to run build-run sequence again.
It would be nice to have watch + serve script:
npm run demo:dev

it needs to build both apps, watch and serve them until being stopped (Ctrl+C)

**Comment by hgraphql** [comment]
updated dev workflow, please see `scripts` in `package.json` file.

it should be easier to dev, just run `npm run dev` to have watching on the lib and example
