### ISSUE TITLE
new social thumbnail for repo

### ISSUE THREAD

**Issue by itsbrandondev** [hgraph-io/hedera-walletconnect-utils#44]
i will be implementing a new thumbnail graphic for when the repo is shared on social media (within the repo settings). this is to encourage greater visibility, consistency and accessibility of the initiative and elevate the working group while development is underway. it can be removed afterwards or updated.

pinging @hgraphql here just to see if this kind of thing fits the scope of the project here. i like the visibility and transparency if it is related to the project and impacts the repo even if non-technical. gives folks the ability to have input. let me know thoughts/feeback on that approach.

**Comment by hgraphql** [comment]
@itsbrandondev sounds great

**Comment by itsbrandondev** [comment]
hey @hgraphql how about this? will really help when sharing the repo 👍 

![Hgraph_WalletConnect-Repo_Cover-V1](https://github.com/hgraph-io/hedera-walletconnect-utils/assets/95549232/bbf18a9e-caf0-4f2f-88ab-e1e1fcf06797)

**Comment by hgraphql** [comment]
> hey @hgraphql how about this? will really help when sharing the repo 👍
> 
> ![Hgraph_WalletConnect-Repo_Cover-V1](https://user-images.githubusercontent.com/95549232/285297129-bbf18a9e-caf0-4f2f-88ab-e1e1fcf06797.png)

looks great, lets do it. I think you should have the ability to edit with your github role on this repo with via https://github.com/hgraph-io/hedera-walletconnect-utils/settings

if not, please let me know

@itsbrandondev

**Comment by itsbrandondev** [comment]
yup @hgraphql im all good, closing this issue 👍
