### ISSUE TITLE
Update issue templates

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#45]
**User story**
As a ticket(issue) taker, I'd like to have more clearly defined acceptance criteria when working on a task.

**Acceptance Criteria**
All current issue templates have an additional field that specifies an optional section for user stories & acceptance criteria.

**Comment by itsbrandondev** [comment]
hey @hgraphql updated info for this task

**Comment by itsbrandondev** [comment]
also linking this here from the HIP-820 discussions

https://github.com/hashgraph/hedera-improvement-proposal/discussions/819#discussioncomment-7509931

**Comment by hgraphql** [comment]
> also linking this here from the HIP-820 discussions
> 
> [hashgraph/hedera-improvement-proposal#819 (reply in thread)](https://github.com/hashgraph/hedera-improvement-proposal/discussions/819#discussioncomment-7509931)

@itsbrandondev was this meant for a different issue?

**Comment by itsbrandondev** [comment]
i thought you wanted this referenced in this issue feel free to remove if not relevant 👍 @hgraphql

**Comment by hgraphql** [comment]
> i thought you wanted this referenced in this issue feel free to remove if not relevant 👍 @hgraphql

created new issue - https://github.com/hgraph-io/hedera-walletconnect-utils/issues/48

**Comment by itsbrandondev** [comment]
ah @hgraphql i see you were referencing issue templates for this repo gotcha my bad. i'll be working on this

**Comment by hgraphql** [comment]
hi @itsbrandondev I've also assigned this ticket to me. Please let me know if you'd like me to take this on or if there is more direction needed 

the idea is that the files in this folder - https://github.com/hgraph-io/hedera-walletconnect-utils/tree/release/hip-820/.github/ISSUE_TEMPLATE have 1 additional section that highlights a list of things a developer would need to do to close a ticket. something like:

**Acceptance criteria**
- [ ] The button is disabled while submitting the form
...

**Comment by itsbrandondev** [comment]
this makes sense, i will review this and let you know if i have any questions @hgraphql

**Comment by hgraphql** [comment]
@itsbrandondev closing this
