### ISSUE TITLE
Test integration with react native

### ISSUE THREAD

**Issue by itsbrandondev** [hgraph-io/hedera-walletconnect-utils#48]
Since https://github.com/hashgraph/hedera-sdk-js does NOT support react native bare, does that mean that this library cannot support react native bare because of the dependency on the hedera javascript sdk?

Test whether or not this library has issues (because of importing the @hashgraph javascript sdk) with a react native implementation (not utilizing expo). Provide potential solutions that are found.

timebox: 2 hours

**Comment by hgraphql** [comment]
after testing, issues have occured with this helper library for the same reason
