### ISSUE TITLE
Avoid to keep PrivateKey in HederaWallet object

### ISSUE THREAD

**Issue by franfernandez20** [hgraph-io/hedera-walletconnect-utils#5]
I propose changing the approach to sign transactions and messages. I would avoid storing the PrivateKey in an object and delegate its use to a signer element like Client or Wallet.

Example for transactions:
 
 ``` ts
// [...]
await transaction.sign(this._privateKey)
// [...]
```
to 
``` ts
// [...]
await transaction.signWithOperator(this._client)
// [...]
```

Example for messages:
``` ts
  public signMessages(bytes: string[]): HederaSignMessageResponse {
    return {
      signatures: bytes.map((bytes) => {
        const buf = Buffer.from(bytes, 'base64')
        this._client._operator?.transactionSigner(buf)
        const signedMessage = this._privateKey.sign(buf)
        return Buffer.from(signedMessage).toString('base64')
      }),
    }
  }
```
to 
``` ts
// [...]
 this._wallet = new Wallet(accountId, privateKey)
// [...]
  public signMessages(bytes: string[]): HederaSignMessageResponse {
    return {
      signatures: bytes.map((bytes) => {
        const buf = Buffer.from(bytes, 'base64')
        const signedMessage = await this._wallet.sign([buf])
        // or 
        // const signedMessage = await this._client.getOperator().transactionSigner(buf)
        return Buffer.from(signedMessage).toString('base64')
      }),
    }
  }

**Comment by hgraphql** [comment]
agreed. thanks for raising this issue

**Comment by Volind** [comment]
Yes, let's pass a transaction signer callback instead
of a key, this will allow wallet app to use hardware wallet for signing.

**Comment by hgraphql** [comment]
stubbed out implementation using `Wallet` from `@hashgraph/sdk` here. untested yet, but this should allow us to delegate key management https://github.com/hgraph-io/hedera-walletconnect-utils/blob/c919efd356e417ac857bbc05105175a647418b60/src/lib/wallet/base.ts#L100

**Comment by itsbrandondev** [comment]
updated weekly goal for this issue @hgraphql

**Comment by hgraphql** [comment]
@itsbrandondev sounds good

it's being address here https://github.com/hgraph-io/hedera-walletconnect-utils/blob/f6f4b09671f5933ea19cca9ddc52ea73d68c574c/src/lib/wallet/index.ts#L43

though it's hard to share / get a review until it's demonstrated in a demo

**Comment by hgraphql** [comment]
new structure involves passing a signer / wallet https://github.com/hgraph-io/hedera-walletconnect-utils/blob/c691b9f96115a4484c56173b3f302937fc963495/src/lib/wallet/index.ts#L144

**Comment by hgraphql** [comment]
marking as closed as the lib is now using the Wallet signer
