### ISSUE TITLE
Issue terminating connections

### ISSUE THREAD

**Issue by itsbrandondev** [hgraph-io/hedera-walletconnect-utils#50]
Wallawallet has mentioned they have encountered an error terminating sessions with WC. Gather more information to fill out a bug report template, or give steps to reproduce.

**Comment by itsbrandondev** [comment]
just checking in to see if we can close this issue @hgraphql

**Comment by hgraphql** [comment]
we're looping through sessions & pairing strings and closing these strings. We can use the demo to replicate this issue, though at this moment we have not replicated by using this method. closing, but will re-open when we can replicate
