### ISSUE TITLE
Discussion on HIP-820 hedera_signMessage

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#51]
@pwoosam had suggested updates in the main branch (pre HIP-820)

- https://github.com/hgraph-io/hedera-walletconnect-utils/pull/3
- https://github.com/pwoosam/hedera-walletconnect-utils/blob/b629e04c5363ef160a488ad10e3458b209abd69f/src/lib/wallet.ts
- related: https://github.com/hashgraph/hedera-improvement-proposal/discussions/819#discussioncomment-7509931

However, the sign message functionality have changed, in part because of the spec for `hedera_signMessage`

This issue has an update to HIP-820 to have a spec closer to the functionality of the sdks

**Comment by itsbrandondev** [comment]
just checking in on this issue @BeeJeeNinja @hgraphql

**Comment by hgraphql** [comment]
opened a PR here - https://github.com/hashgraph/hedera-improvement-proposal/pull/840

Doesn't seem like much interest in making changes. Will confirm in our meeting tomorrow
