### ISSUE TITLE
Java implementation

### ISSUE THREAD

**Issue by itsbrandondev** [hgraph-io/hedera-walletconnect-utils#63]
**Is your feature request related to a problem? Please describe.**
a Hedera wallet provider is looking to support their users, most of whom are on mobile

**Describe the solution you'd like**
they highlight that a Java implementation would resolve this

**Describe alternatives you've considered**
none at this time

**Additional context**
the wallet is Wombat Wallet and the request was sent via email @hgraphql

**Comment by hgraphql** [comment]
@itsbrandondev 

closing this as a near duplicate to https://github.com/hgraph-io/hedera-walletconnect-utils/issues/17
