### ISSUE TITLE
batch transactions - via additional method

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#64]
**Is your feature request related to a problem? Please describe.**
https://github.com/hgraph-io/hedera-walletconnect-utils/issues/10 provides a method for batch transactions.

This ticket provides an alternate solution by allowing the first param in the `request.params` array to be an array of method bodies (such as a transaction body). An example of an update looks like:

``` typescript
public parseSessionRequest(
    event: Web3WalletTypes.SessionRequest,
    // optional arg to throw error if request is invalid, call with shouldThrow = false when calling from rejectSessionRequest as we only need id and top to send reject response
    shouldThrow = true,
  ): {
    ...
    body?: Transaction | Transaction[] | Query<any> | Query<any>[] | Uint8Array[] | undefined
    accountId?: AccountId
```

**Describe the solution you'd like**
Add a method that processes multiple transactions on the network (similar to `hedera_signTransactionAndSend`)

**Comment by itsbrandondev** [comment]
updated project info for this task @hgraphql

**Comment by hgraphql** [comment]
@BeeJeeNinja please add work you've completed on this - https://github.com/hgraph-io/hedera-walletconnect-utils/pull/68, in a branch with base `release/hip-820`. I'd like to see a clean diff without other unrelated changes. Thanks!

**Comment by hgraphql** [comment]
closing, good work.
