### ISSUE TITLE
review method names in HIP and vote if necessary: i.e. `hedera_signTransactionAndSend` vs `signAndExecuteTransaction`

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#7]
This is more of a discussion topic for the group. We just want to see if there's any suggested changes for the core set of functions or if we're good to proceed using this naming scheme.

https://deploy-preview-820--hedera-hips.netlify.app/hip/hip-820#how-to-teach-this

<img width="382" alt="Screenshot 2023-10-31 at 2 19 16 PM" src="https://github.com/hgraph-io/hedera-walletconnect-utils/assets/105378986/d3a1505b-9aeb-4bd6-8d0e-a7d6ab905f2b">

**Comment by hgraphql** [comment]
@itsbrandondev just checking in to make sure that we review this on the call on friday

**Comment by hgraphql** [comment]
@itsbrandondev moved this status to in progress

**Comment by itsbrandondev** [comment]
sounds good : )

**Comment by hgraphql** [comment]
> sounds good : )

💯

**Comment by hgraphql** [comment]
no requests for changes, so closing the issue
