### ISSUE TITLE
Payloads

### ISSUE THREAD

**Issue by hgraphql** [hgraph-io/hedera-walletconnect-utils#79]
## Background

**What is JSON-RPC?** JSON-RPC is a stateless, light-weight remote procedure call (RPC)
protocol. (https://www.jsonrpc.org/specification)

A remote procedure call is a software communication protocol that one program can use to request
a service from a program located in another computer on a network without having to understand
the network's details.

This type of protocol works very nicely in the context of dApps and Wallets that interact over a
network with either side not knowing the details of implementation of the other side (i.e. what
programing language they use).

gRPC is another type of remote procedure call framework - this is the one the Hedera API
services use. We see an example of a remote procedure call service architecture in practice by
examining how transactions occur on the Hedera network. Many wallets and dApps are written in
javascript, go, c#, in addition to others and utilize sdks that call the gRPC endpoints for
Hedera services.

Servers operating Hedera services receive these calls and execute code written in Java. The
artifacts or outputs of the Java code change the consensus state that participating nodes agree
upon and share via record files populated to s3 endpoints. Both the callers (wallets / dapps
written in myriad languages) and the executers (Hedera consensus nodes running Java code) do not
need to know the implementation details of each other, just the desired outcomes.

## Implementation

**WalletConnect JSON-RPC payloads**

WalletConnect is designed to be chain agnostic because it allows arbitrary sending and receiving
of JSON-RPC payloads. A distributed ledger can define a JSON-RPC structure and begin to utilize
the infrastructure WalletConnect provides to send messages between dApps and wallets.

Hedera is utilizing the Hedera Improvement Proposal process to define the JSON-RPC structure.
[HIP-820](https://hips.hedera.com/hip/hip-820)

**Completion of this ticket** The completion of this issue resolves the delta between HIP-820
and this reference implementation.

**hedera_signTransactionAndSend**

_Request:_

```json
{
  "jsonrpc": "2.0",
  "id": "<some-request-id>",
  "method": "hedera_signTransactionAndSend",
  "params": {
    "signerAccountId": "<0.0.123>",
    "signedTransaction": "<a base64 encoding of the protobuf encoded Hedera API SignedTransaction message>"
  }
}
```

_Response:_

```json
{
  "jsonrpc": "2.0",
  "id": "<the-request-id>",
  "result": {
    "precheckCode": "<an integer representing the [ResponseCodeEnum] value returned from the Hedera Node, which may indicate success or failure.>",
    "transactionId": "<a string encoded transaction identifier of the signed message that was sent to the Hedera node, in <shard>.<realm>.<number>@<seconds>.<nanos> format.>",
    "nodeId": "<a string encoded transaction identifier of the Hedera Gossip Node’s Account that the transaction was submitted to, in <shard>.<realm>.<number> format>",
    "transactionHash": "<base64 encoding of the SHA384 digest of the signedTransactionBytes of the Transaction message that was submitted to the Hedera Network.>"
  }
}
```

**hedera_signTransactionBody**

_Request:_

```json
{
  "jsonrpc": "2.0",
  "id": "<some-request-id>",
  "method": "hedera_signTransactionBody",
  "params": {
    "signerAccountId": "<0.0.123>",
    "transactionBody": "<a base64 encoding of the protobuf encoded Hedera API TransactionBody message>"
  }
}
```

_Response:_

```json
{
  "jsonrpc": "2.0",
  "id": "<the-request-id>",
  "result": {
    "signatureMap": "<a base64 encoding of the protobuf encoded Hedera API SignatureMap message>"
  }
}
```

**hedera_sendTransactionOnly**

_Request:_

```json
{
  "jsonrpc": "2.0",
  "id": "<the-request-id>",
   "method": "hedera_sendTransactionOnly",
  "params": {
    "signedTransaction": "<a base64 encoding of the protobuf endoded Hedera API SignedTransaction message>",
  }
}
```

_Response:_

```json
{
  "jsonrpc": "2.0",
  "id": "<the-request-id>",
  "result": {
    "precheckCode": "<an integer representing the [ResponseCodeEnum] value returned from the Hedera Node, which may indicate success or failure.>",
    "transactionId": "<a string encoded transaction identifier of the signed message that was sent to the Hedera node, in <shard>.<realm>.<number>@<seconds>.<nanos> format.>",
    "nodeId": "<a string encoded transaction identifier of the Hedera Gossip Node’s Account that the transaction was submitted to, in <shard>.<realm>.<number> format>",
    "transactionHash": "<base64 encoding of the SHA384 digest of the signedTransactionBytes of the Transaction message that was submitted to the Hedera Network.>"
  }
}
```

**hedera_signQueryAndSend**

_Request:_

```json
{
  "jsonrpc": "2.0",
  "id": "<some-request-id>",
  "method": "hedera_signQueryAndSend",
  "params": {
    "query": "<a base64 encoding of the protobuf encoded Hedera API Query message.>"
  }
}
```

_Response:_

```json
{
  "jsonrpc": "2.0",
  "id": "<the-request-id>",
  "result": {
    "response": "<a base64 encoding of the protobuf encoded Hedera API Response>"
  }
}
```

**hedera_signMessage**

_Request:_

```json
{
  "jsonrpc": "2.0",
  "id": "<some-request-id>",
  "method": "hedera_signMessage",
  "params": {
    "message": "<a plain text string to present to the user prior to authorizing a signature>"
  }
}
```

_Response:_

```json
{
  "jsonrpc": "2.0",
  "id": "<the-request-id>",
  "result": {
    "signatureMap": "<a base64 encoding of the protobuf endoded Hedera API SignatureMap message>"
  }
}
```

**hedera_getNodeAddresses**

_Request:_

```json
{
  "jsonrpc": "2.0",
  "id": "<some-request-id>",
  "method": "hedera_getNodeAddresses"
}
```

_Response:_

```json
{
  "jsonrpc": "2.0",
  "id": "<the-request-id>",
  "result": {
    "nodes": "<an array of strings formatted in the <shard>.<realm>.<num> format identifying an Hedera Address>"
  }
}
```

**Acceptance criteria** This issue is complete when:

- [x] This issue and HIP-820 are in sync with request and response payloads for
      `hedera_signTransactionAndSend`
- [x] This issue and HIP-820 are in sync with request and response payloads for
      `hedera_signTransactionBody`
- [x] This issue and HIP-820 are in sync with request and response payloads for
      `hedera_sendTransactionOnly`
- [x] This issue and HIP-820 are in sync with request and response payloads for
      `hedera_signQueryAndSend`
- [x] This issue and HIP-820 are in sync with request and response payloads for
      `hedera_signMessage`
- [x] This issue and HIP-820 are in sync with request and response payloads for
      `hedera_getNodeAddresses`

**How to contribute** Make suggestions to edit this issue and/or suggest a pull request into
HIP-820

**Comment by itsbrandondev** [comment]
added some metadata to this task @hgraphql this can be resolved while HIP-820 is still in last call right?

**Comment by hgraphql** [comment]
> added some metadata to this task @hgraphql this can be resolved while HIP-820 is still in last call right?

@itsbrandondev yep, last call for changes is how I interpret the process

**Comment by hgraphql** [comment]
closing issue per groups decision and standardization
