### ISSUE TITLE
Pushing back "3+ Wallets integrated" milestone

### ISSUE THREAD

**Issue by itsbrandondev** [hgraph-io/hedera-walletconnect-utils#85]
wallets should postpone the Dec 1st milestone of "initial wallet integrations" for WalletConnect to allow for a few final things to settle and to ensure wallets have what they need for integrating.

**rationale:**

- HIP-820 has changed quite a bit
- payload types need some revisions
- general consensus from the group

**resolution:**

it's actually been really beneficial to raise these topics and work through these things this week and we expect this will be resolved with clarity by Monday (end of day) or earlier.

feedback/questions welcome 🙏

**Comment by hgraphql** [comment]
closing as coordinated outside of github
